version: '1'

services:
  gophish:
    image: gophish/gophish:latest
    container_name: gophish
    ports:
      - "8080:8080"
      - "8000:80"
      - "3333:3333"
    volumes:
      - gophishdata:/opt/gophish
    environment:
      - GOPHISH_INITIAL_ADMIN_PASSWORD = "yourPassword"
  mailhog:
    image: mailhog/mailhog:latest
    container_name: mailhog
    ports:
      - "8025:8025"
      - "1025:1025"

volumes:
    gophishdata:
